/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EncouragerGui;

import encourager.Encourager;
import java.util.Scanner;

/**
 *
 * @author ookie
 */



public class EncouragerGui extends javax.swing.JFrame {

    /**
     * Creates new form EncouragerGui
     */
    public EncouragerGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yourNeed = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ourEncouragement = new javax.swing.JTextArea();
        encourageMe = new javax.swing.JButton();
        responseYes = new javax.swing.JButton();
        responseNo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("The Encourager");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("What are you in need of today? ");

        yourNeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourNeedActionPerformed(evt);
            }
        });

        ourEncouragement.setColumns(20);
        ourEncouragement.setRows(5);
        jScrollPane1.setViewportView(ourEncouragement);

        encourageMe.setText("Encourage Me");
        encourageMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encourageMeActionPerformed(evt);
            }
        });

        responseYes.setText("Yes");
        responseYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responseYesActionPerformed(evt);
            }
        });

        responseNo.setText("No");
        responseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responseNoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Is there anything else we can encourage you with?");

        jLabel4.setText("Where we aim to lift you up in the name of Jesus!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(responseYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(responseNo)
                        .addGap(83, 83, 83))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yourNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(encourageMe)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourNeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(encourageMe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responseYes)
                    .addComponent(responseNo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
            //Scanner object initiated
        static Scanner sc = new Scanner(System.in);
//        //String used to gague response
//        static String again;
        static String need;
        
        public static void outro() {
           //Ending message (Will run after loop runs)
           System.out.println("\n Thank You for using The Encourager. May the Lord"
                    + " bless you in Your walk with Him! \n");
           System.exit(0);
        }
        
    public static void runCode() {
    
        
        
        System.out.println("What are you in need of today?\n");
        
        
            //Read in response
            need = sc.next();

            if (need.equalsIgnoreCase("nothing") || need.equalsIgnoreCase("no") || 
                    need.equalsIgnoreCase("exit")|| need.equalsIgnoreCase("stop")) {
                //Stop program
                outro();
            }
            
            //What if response isn't what I accounted for?
            //While "answer" is not equal to x AND not equal to y AND not equal to z...
            while(!need.equalsIgnoreCase("money") && !need.equalsIgnoreCase("bills") && 
                !need.equalsIgnoreCase("finances") && !need.equalsIgnoreCase("cash") && 
                !need.equalsIgnoreCase("tithing") && !need.equalsIgnoreCase("provision") &&
                !need.equalsIgnoreCase("healing") && !need.equalsIgnoreCase("healer") && 
                !need.equalsIgnoreCase("health") && !need.equalsIgnoreCase("sick") && 
                !need.equalsIgnoreCase("sickness") && !need.equalsIgnoreCase("doctor") &&
                !need.equalsIgnoreCase("depression") && !need.equalsIgnoreCase("depressed") && 
                !need.equalsIgnoreCase("uplift") && !need.equalsIgnoreCase("uplifted") && 
                !need.equalsIgnoreCase("encouragement") && !need.equalsIgnoreCase("depression") && 
                !need.equalsIgnoreCase("depressed") && 
                !need.equalsIgnoreCase("uplift") && !need.equalsIgnoreCase("uplifted") && 
                !need.equalsIgnoreCase("encouragement") && !need.equalsIgnoreCase("pray") && 
                !need.equalsIgnoreCase("prayer") && !need.equalsIgnoreCase("wisdom") && 
                !need.equalsIgnoreCase("wise") && !need.equalsIgnoreCase("proverbs") && 
                !need.equalsIgnoreCase("learning") && !need.equalsIgnoreCase("learn") &&
                !need.equalsIgnoreCase("love") && !need.equalsIgnoreCase("lust") && 
                !need.equalsIgnoreCase("marriage") && !need.equalsIgnoreCase("engagement") && 
                !need.equalsIgnoreCase("sex")) {
            System.out.println("\n I'm sorry, we don't recognize that answer. Please try again. \n"
                    + "What's your need?");
            need = sc.next();
            if (need.equalsIgnoreCase("nothing") || need.equalsIgnoreCase("no") || 
                    need.equalsIgnoreCase("exit")|| need.equalsIgnoreCase("stop")) {
                outro();
                }
            }
                
            //Finance options we recognize for comparison
            if (need.equalsIgnoreCase("money") || need.equalsIgnoreCase("bills") || 
                need.equalsIgnoreCase("finances") || need.equalsIgnoreCase("cash") || 
                need.equalsIgnoreCase("tithing") || need.equalsIgnoreCase("provision")) {    
            encourager.Finances.finResp();
            }

            //Healing options we recognize for comparison
            if (need.equalsIgnoreCase("healing") || need.equalsIgnoreCase("healer") || 
                need.equalsIgnoreCase("health") || need.equalsIgnoreCase("sick") || 
                need.equalsIgnoreCase("sickness") || need.equalsIgnoreCase("doctor")) {    
            encourager.Healing.healResp();
            }

            //Encouragement options we recognize for comparison
            if (need.equalsIgnoreCase("depression") || need.equalsIgnoreCase("depressed") || 
                need.equalsIgnoreCase("uplift") || need.equalsIgnoreCase("uplifted") || 
                need.equalsIgnoreCase("encouragement")) {    
            encourager.Encouragement.encResp();
            }

            //Prayer options we recognize for comparison
            if (need.equalsIgnoreCase("pray") || need.equalsIgnoreCase("prayer")) {    
            encourager.Prayer.prayResp();
            }

            //Wisdom options we recognize for comparison
            if (need.equalsIgnoreCase("wisdom") || need.equalsIgnoreCase("wise") || 
                need.equalsIgnoreCase("proverbs") || need.equalsIgnoreCase("learning") || 
                need.equalsIgnoreCase("learn")) {    
            encourager.Wisdom.wiseResp();
            }

            //Love options we recognize for comparison
            if (need.equalsIgnoreCase("love") || need.equalsIgnoreCase("lust") || 
                need.equalsIgnoreCase("marriage") || need.equalsIgnoreCase("engagement") || 
                need.equalsIgnoreCase("sex")) {    
            encourager.Love.loveResp();
            }
            
            System.out.println("\n\n Thank you for allowing us to encourage you. \n "
                    + "I hope this really helped and ministered to Your need. \n "
                    + "Is there another need we can help you with?\n\n");
            
            //Instantiates need for repsonse
//            again = sc.next();
//
//            while (!again.equalsIgnoreCase("y") && (!again.equalsIgnoreCase("yes"))
//                     && (!again.equalsIgnoreCase("n")) && (!again.equalsIgnoreCase("no"))) {
//            System.out.println("Please answer again but this time using only yes or no...");
//            again = sc.next();
//            }
//            
//            //Go again?
//            if (again.equalsIgnoreCase("no") || again.equalsIgnoreCase("n")) {
//            //Ending message and stop program              
//            outro();
//            }
            
        }
    
    private void encourageMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encourageMeActionPerformed
        // TODO add your handling code here:
        yourNeed.getText();
        
        
        
        runCode();
    }//GEN-LAST:event_encourageMeActionPerformed

    private void yourNeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourNeedActionPerformed
        // TODO add your handling code here:
        need = sc.next();
    }//GEN-LAST:event_yourNeedActionPerformed

    private void responseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responseNoActionPerformed
        Encourager.outro();
    }//GEN-LAST:event_responseNoActionPerformed

    private void responseYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responseYesActionPerformed
        // TODO add your handling code here:
        //again = sc.next("Yes"); - May not need
        yourNeed.setText("");
        ourEncouragement.setText("");
    }//GEN-LAST:event_responseYesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncouragerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncouragerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncouragerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncouragerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncouragerGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encourageMe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ourEncouragement;
    private javax.swing.JButton responseNo;
    private javax.swing.JButton responseYes;
    private javax.swing.JTextField yourNeed;
    // End of variables declaration//GEN-END:variables
}
